spring.application.name=learning_Springai
server.port= 8080

spring.ai.huggingface.chat.api-key=${hugging_face}
spring.ai.huggingface.chat.base-url=[https://api-inference.huggingface.co/models/google/gemma-2-9b-it](https://api-inference.huggingface.co/models/google/gemma-2-9b-it)