spring.application.name=learning_Springai
server.port= 8081

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.ollama.chat.options.model=qwen2.5-coder:7b

spring.ai.vectorstore.chroma.client.host=http://localhost
spring.ai.vectorstore.chroma.client.port=9000
spring.ai.vectorstore.chroma.initialize-schema=true
spring.ai.vectorstore.chroma.collection-name=university_notes

spring.ai.vectorstore.chroma.client.tenant=default_tenant
spring.ai.vectorstore.chroma.client.database=default_database